server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/harinera
    username: postgres
    password: Elperri2023.
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
